### ISSUE TITLE
configurable path for csv files

### ISSUE THREAD

**Issue by Andre1Becker** [ZuinigeRijder/hyundai_kia_connect_monitor#55]
**Is your feature request related to a problem? Please describe.**
Not a problem, more a convenience thing ;-)

**Describe the solution you'd like**
A paramater in the monitor.cfg to configure a path where the csv files should get stored. I'm trying to figure this out on my own, but im not even close a programmer :-)

**Describe alternatives you've considered**
none.

**Additional context**
I'm currently trying to get this working within a docker container. So it would be nice to separate the script from the output data to easily access the files from other external programs

**Comment by ZuinigeRijder** [comment]
I think I implemented this in release R3.17.0: https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/releases/tag/R3.17.0

- made it possible to run the python scripts in another directory, the configuration files are searched on the directory where the python scripts are located

So it is not a parameter, but you can get in another (sub)directory where the csv files are located.

Examples:
- python ..\monitor.py
- python ..\summary.py

You can also specify the full path to the Python scripts.

**Comment by Andre1Becker** [comment]
I didn't even think about that. Works like a charm!

Tanks!
