### ISSUE TITLE
error running monitor.py

### ISSUE THREAD

**Issue by Symbiot78** [ZuinigeRijder/hyundai_kia_connect_monitor#57]
seeing the following error when running monitor.py

I am running the package in a docker container as described by Andre1Becker
`Idea is that thereafter you can analyze the information over time,
e.g. with Excel:
- odometer over time
- average drive per day/week/month over time
- SOC over time
- 12V battery over time
- charging pattern over time
- visited places
: No such file or directory
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
./monitor.py: line 39: from: command not found
./monitor.py: line 40: from: command not found
./monitor.py: line 41: from: command not found
./monitor.py: line 42: from: command not found
./monitor.py: line 43: syntax error near unexpected token `('
./monitor.py: line 43: `from monitor_utils import ('
`

**Comment by Symbiot78** [comment]
so i may be a muppet.. ran python monitor.py

`python monitor.py
Traceback (most recent call last):
  File "/opt/hyundai_monitor/monitor.py", line 42, in <module>
    from hyundai_kia_connect_api import VehicleManager, Vehicle, exceptions
ImportError: cannot import name 'VehicleManager' from 'hyundai_kia_connect_api' (unknown location)`

**Comment by ZuinigeRijder** [comment]
See [README](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor?tab=readme-ov-file#how-to-install-python-packages-and-hyundai_connect_monitor):
move the hyundai_kia_connect_api subfolder of hyundai_kia_connect_api-[version] underneath hyundai_kia_connect_monitor.

So you will have the structure hyundai_kia_connect_monitor/hyundai_kia_connect_api

**Comment by Symbiot78** [comment]
yeah.. I kindda figured out some stuff after posting..

However it seems to run now. But..

I keep getting a login error..

I think it may be because I have a   "     in my password.
I tried escaping with \"

but to no avail.. is this the wrong way of doing it?

**Comment by ZuinigeRijder** [comment]
I think this is a restriction of the hyundai_kia_connect_api, so probably it is best to avoid " and ' in the password. 
The escape character is \ but do not know if this would work. You can also try \u0022 instead of "

If that does not work, it is better to change your password not to contain "and '

**Comment by Symbiot78** [comment]
I changed the pw.. that helped.
