### ISSUE TITLE
monitor.py does not generate monitor.dailystats.csv

### ISSUE THREAD

**Issue by libseide** [ZuinigeRijder/hyundai_kia_connect_monitor#58]
**Describe the bug**
monitor.py does not generate monitor.dailystats.csv

**Versions**
* hyundai_kia_connect_monitor version: R3.20.0
* Python version: 3.11
* Operating System: Debian 12

**Screenshots**
![Debug](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/assets/73787040/a36cd7e8-ed7d-4c22-8313-50e7bd832f10)

application Bluelink is OK, monitor.csv and monitor.tripinfo.csv is OK

Thanks Libor

**Comment by ZuinigeRijder** [comment]
Which version of hyundai_kia_connect_api are you using?
Which car do you have?
Which region?

For me it is still working for my IONIQ 5 in Europe with Bluelink, I am using hyundai_kia_connect_api v3.17.5.

**Comment by libseide** [comment]
Hi !,

Thank you for your quick response.
My car is Hyundai Kona SX2 (ICE version) in Europe.
(
I had to change: line 341 in monitor.py  (because ICE):
line = f"{newest_updated_at}, {location_longitude}, {location_latitude}, {vehicle.engine_is_running}, {vehicle.car_battery_percentage}, {odometer:.1f},  0, 0, 0, {geocode}, {ev_driving_range}"  # noqa
)
I am using hyundai_kia_connect_api v3.17.8. (same problem on older version as well)

I'm sorry, but I'm not a programmer and I only have a vague idea of what's going on.

Thanks very much for your time.

Libor

________________________________
Od: Zuinige Rijder ***@***.***>
Odesláno: středa 27. března 2024 15:56
Komu: ZuinigeRijder/hyundai_kia_connect_monitor ***@***.***>
Kopie: libseide ***@***.***>; Author ***@***.***>
Předmět: Re: [ZuinigeRijder/hyundai_kia_connect_monitor] monitor.py does not generate monitor.dailystats.csv (Issue #58)


Which version of hyundai_kia_connect_api are you using?
Which car do you have?
Which region?

For me it is still working for my IONIQ 5 in Europe with Bluelink, I am using hyundai_kia_connect_api v3.17.5.

**Comment by ZuinigeRijder** [comment]
Ok, so the {vehicle.ev_battery_percentage}, {vehicle.ev_battery_is_charging}, {vehicle.ev_battery_is_plugged_in} is not filled in, so apparently I have to be prepared in monitor.py that this does not need to be filled. 

However, in the debug screenshot I see that the signin does not succeed. I am wondering why  you can still get the other information. Or did you fix there something? Or did it succeed when you tried again?

**Comment by libseide** [comment]
Thank you, I didn't change anything else and the rest loads correctly every time, so monitor.csv and moditor.tripinfo.csf are fine, only monitor.dailystats.csv is missing.
________________________________
Od: Zuinige Rijder ***@***.***>
Odesláno: středa 27. března 2024 21:18
Komu: ZuinigeRijder/hyundai_kia_connect_monitor ***@***.***>
Kopie: libseide ***@***.***>; Author ***@***.***>
Předmět: Re: [ZuinigeRijder/hyundai_kia_connect_monitor] monitor.py does not generate monitor.dailystats.csv (Issue #58)


Ok, so the {vehicle.ev_battery_percentage}, {vehicle.ev_battery_is_charging}, {vehicle.ev_battery_is_plugged_in} is not filled in, so apparently I have to be prepared in monitor.py that this does not need to be filled.

However, in the debug screenshot I see that the signin does not succeed. I am wondering why you can still get the other information. Or did you fix there something? Or did it succeed when you tried again?

**Comment by ZuinigeRijder** [comment]
I assume that for an ICE vehicle.daily_stats is not filled. Note that outside Europe this is also not filled, even for an EV. Can you run:

`python debug.py`

and redirect the standard output and error output to a file or copy/paste the output in a text file (and you can also remove some privacy information if you are concerned) and email this to me? My email is @gmail.com with me username prefixed.

**Comment by ZuinigeRijder** [comment]
Thanks for the debug log. I did send you an email back some days ago.

Indeed I see you still get the "get_authorization_code_with_redirect_url failed". I do not have this.
I looked into the source code of hyundai_kia_connect_api KiaUvoApiEU.py and I see that if this exception occurs, it does a fallback to login with _get_authorization_code_with_form and that succeeds. So probably this is the intention (I am not the author of that code).

I also looked into KiaUvoApiEU.py, why daily_stats is not filled. And I see the following code on line 352 and 379:

             if (
                vehicle.engine_type == ENGINE_TYPES.EV
                or vehicle.engine_type == ENGINE_TYPES.PHEV
            ): 


You can try to modify KiaUvoApiEU.py on both lines into (please make sure indentation is correct):

            if (
                vehicle.engine_type == ENGINE_TYPES.EV
                or vehicle.engine_type == ENGINE_TYPES.PHEV
                or vehicle.engine_type == ENGINE_TYPES.ICE
            ):



Thereafter, see if you get the daily_stats or if that fails.

**Comment by libseide** [comment]
Thank you very much for your kind reply. I will try it today and post the
result.
We can close the request, obviously there is nothing left for you.

Libor

ne 31. 3. 2024 v 22:03 odesílatel Zuinige Rijder ***@***.***>
napsal:

**Comment by libseide** [comment]
Yes, that's right, I've tried it. No data available for ICE.

st 3. 4. 2024 v 9:17 odesílatel Zuinige Rijder ***@***.***>
napsal:
