### ISSUE TITLE
UnboundLocalError: cannot access local variable 'state'

### ISSUE THREAD

**Issue by RevolveIT** [ZuinigeRijder/hyundai_kia_connect_monitor#63]
**Describe the bug**
When running python monitor.py

**Versions**
* hyundai_kia_connect_monitor version: R3.250
* Python version: 3.12.5
* Operating System: Windows 10
*  hyndia_kia_connect_api version: 3.22.10

**Description**
When running python monitor.py, I get the following error message:

20240904 20:36:50: Exception: cannot access local variable 'state' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Hyundai\monitor.py", line 429, in handle_vehicles
    manager.update_all_vehicles_with_cached_state()  # needed >= 2.0.0
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hyundai\hyundai_kia_connect_api\VehicleManager.py", line 85, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
  File "C:\Hyundai\hyundai_kia_connect_api\VehicleManager.py", line 90, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "C:\Hyundai\hyundai_kia_connect_api\KiaUvoApiAU.py", line 259, in update_vehicle_with_cached_state
    self._update_vehicle_drive_info(vehicle, state)
                                             ^^^^^
UnboundLocalError: cannot access local variable 'state' where it is not associated with a value
20240904 20:36:50: Sleeping a minute

**What I Did**

Ran Python monitor.py with monitor.cfg configured as follows (username/password redacted)
```
[monitor]
region = 5
brand = 2
username = 
password = 
pin = 
use_geocode = True
use_geocode_email = True
language = en
odometer_metric = km
include_regenerate_in_consumption = False
```

NOTE: according to the api docs, region = 5 is correct for Australia

**Comment by ZuinigeRijder** [comment]
@RevolveIT Can you also run "python debug.py" and mail me the standard output and error output to my gmail account zuinige.rijder? Maybe that gives me a clue.

It looks like there is something wrong in hyundai_kia_connect_api, maybe the debug.py output gives me a clue.

Which car do you have?

**Comment by ZuinigeRijder** [comment]
@RevolveIT Did you send an email? Did the problem disappear? Otherwise I am going to close this issue.

**Comment by ZuinigeRijder** [comment]
No response after issue was submitted, so I close the issue.
