### ISSUE TITLE
How can I force a full history data download?

### ISSUE THREAD

**Issue by teodorch85** [ZuinigeRijder/hyundai_kia_connect_monitor#67]
Hi!
I am trying to force a full history download but I can't get it to work.
I tried to change in monitor.py 
line 289

FROM
from_month = now  # default only get the current month statistics

TO
from_month = now - relativedelta(months=4)

but it didn't work.

Any ideas? 
Thank you

**Comment by ZuinigeRijder** [comment]
I assume you question is about the daily stats.

Which car do you have?
Which region?

In Europe only about 3 months of history is stored on the (Kia Connect or Bluelink) server. For Hyundai USA only the last 4 trips are stored. For other regions I do not know.

Note that other information is just a snapshot of the latest cached server information, so each time you ask for it, it is stored if it differs. So you have to build up this history, but still you can miss changed data.

**Comment by teodorch85** [comment]
Ioniq 5
EU
I bought the car on the 04th of July, so all data is still in the Bluelink android app.

I am trying to do a full history download for the first time and then I will update every day.

**Comment by ZuinigeRijder** [comment]
You can delete monitor.dailystats.csv and monitor.tripinfo.csv, then monitor.py tries to get the history data from 3 months back.

**Comment by teodorch85** [comment]
I run those commands after deleting the files you mentioned with original monitor.py

python monitor.py
python summary.py sheetupdate
python dailystats.py sheetupdate

and I get 
![image](https://github.com/user-attachments/assets/57ed0ff1-bcde-4c5c-bd02-c118e7b2cb46)

**Comment by teodorch85** [comment]
Managed to get all data in monitor.tripinfo.csv with a change in line 289
  from_month = now - relativedelta(months=3)

![image](https://github.com/user-attachments/assets/624b2432-d3da-4e7b-bc41-08b97cd8cb79)

Now the problem is that monitor.dailystats.csv goes back only until 22/08/2024
I changed in dailystats.py line 37
MAX_QUEUE_LEN = 2000

but still it stops at 22/08

**Comment by ZuinigeRijder** [comment]
The Bluelink API for getting the dailystats info only gets the last 24 days or something around that number. The API for trip info gives the opportunity to go back about 3 months. So that is why there is a difference. I do not know how to get back more dailystats results, but that would be something to be asked at [hyundai_kia_connect_api.](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api
)
