### ISSUE TITLE
Collecting data every 2 hours potentially wakes up the vehicle

### ISSUE THREAD

**Issue by dg362** [ZuinigeRijder/hyundai_kia_connect_monitor#69]
**Describe the bug**
12V battery appears to be used every 2 hours to match timing of this script being run.

**Versions**
* hyundai_kia_connect_monitor version: R3.25.0
* Python version: 3.11.2
* Operating System: Debian Bookworm 12.7

**Description**

I have this script, updated to latest master, which runs as a crontab of
`0 6-22/2 * * *`
So every 2 hours at 0 minutes past the hour, between 06 and 22 daily.

I also have the Hyundai integration in Home Assistant which is set to poll the vehicle every 4 hours (240 minutes), excluding from 22:00 to 06:00

I have a BM2 battery monitor on my Ioniq 6 so I can see the 12V battery.

Looking at recent days, I can see the 12V blip every 2 hours as per screen shot 1 attached.

Looking at around a month ago, the 12V blip is every 4 hours as per Home Assistant which is a wake-up call to the vehicle, as per screen shot 2 attached.

Given the 12V is now every 2 hours, and the only thing scheduled to do that is this script, it suggests it is now waking up the vehicle.
It did not used to do that, but I cannot recall the exact date I updated the script code plus its dependencies to the latest/current version.

**Expected behavior**
The running of this script only reads from the Hyundai servers and cannot make a call to wake up the vehicle.

**Screenshots**
![bm2-20240925-every2hours](https://github.com/user-attachments/assets/e1419cd4-7b2d-4f7c-9099-cc6cc489a90e)

![bm2-20240813-every4hours](https://github.com/user-attachments/assets/2170c44b-876e-4146-980b-8b9434962bca)

**Comment by ZuinigeRijder** [comment]
From which REGION is your IONIQ 6? 
What is the production date of your car?
And do you know if your car the newest ccNC infotainment hardware?

I have an IONIQ 5 from July 2021 and have also a BM2 device and run my scripts every 20 minutes between 6:00 and 22:00 and do NOT see any dips. I do NOT have Home Assistent running.

**Comment by dg362** [comment]
I live in the UK and hence under Europe from a Hyundai perspective.
My car is an Ioniq 6 Ultimate, first registered in Nov-2023, so likely a MY23 model. This still has the Standard Gen5W infortainment hardware.

As a piece of isolation, I have adjusted the cron for this script to run every 4 hours and will see if that causes the 12V blip to revert or not. It's the quickest isolation I can think to run.

**Comment by ZuinigeRijder** [comment]
Another isolation would be to temporarily disable Home Assistent, to see if the blips are no longer there.
And thereafter, the other way around, disable monitor.py and only run Home Assistent.

**Comment by dg362** [comment]
Yes, I intend to isolate Home Assistant too.
As I only monitor between 06:00-22:00 I may need 2 days to complete the isolations of:

- Script timing - this has already changed so I can monitor this morning
- No Home Assistant and script back at the original frequency of every 2 hours
- Home Assistant every 4 hours but no script
- Neither Home Assistant nor script running

**Comment by ZuinigeRijder** [comment]
Great. Probably start with the last, Neither Home Assistant nor script running, to rule out other 3-party apps.

**Comment by dg362** [comment]
Looks like I need to look into Home Assistant integration and not this script. Apologies.

I stopped the script and left HA running. Was still seeing blips at a frequency greater than the 4 hour poll interval set.
At 15:45 I stopped HA, which would mean at least 1 more poll if not 2 before 22:00 when it stops polling overnight. And since stopping HA there have been no more blips.

![bm2-20240927](https://github.com/user-attachments/assets/db2946af-ff2f-4152-abd6-951525b7b07a)


I've re-enabled the script but left HA disabled and will check this again tomorrow for completeness to make sure I still see no 12V blips (outside the car managing the 12V as it needs to). In all likelihood that will show nothing wrong with this script if I'm seeing something other users are not, so I'll close this issue then.

**Comment by ZuinigeRijder** [comment]
I thought HA also had an option not to refresh by setting "Force Refresh Interval (min)" very high and by not calling force_update in your scripts, but only "update":

- update: get latest cached vehicle data
- force_update: this will make a call to your vehicle to get its latest data, do not overuse this!

Do you really need the force update/force refresh in HA or do you trigger a refresh by some action?

![Configuration](https://github.com/user-attachments/assets/e447fa89-22df-409e-8e79-aa592d2394ee)

**Comment by dg362** [comment]
My HA config was set to a scan of 120 mins, refresh of 240 mins, no force refresh between 22:00 and 06:00, geolocation disabled, as per screenshot below.

![ha-config-hyundai](https://github.com/user-attachments/assets/9f040008-c7d6-4b50-9ca8-74bfd02d24c4)


Anyway, I will close this ticket because there is nothing wrong with the script as the 12V blip never occurs with just the script running and HA not. I will investigate HA integration further with the developer - apologies for the false reporting.

**Comment by ZuinigeRijder** [comment]
This may be a side effect of that last_updated_at is send wrongly by the server with a 2 hours difference 50% of the time.

See [this HA issue](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/931#issuecomment-2368297777).

Side effect can be that too often force update is called.
