### ISSUE TITLE
MQTT summary error

### ISSUE THREAD

**Issue by rpositive** [ZuinigeRijder/hyundai_kia_connect_monitor#73]
**Describe the bug**
When running summary.py with MQTT config in monitor.cfg I get the following error:
20241222 01:26:58: ERROR: MQTT connect Exception: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details, sleeping a minute
Traceback (most recent call last):
  File "/share/Hyundai_Kona/mqtt_utils.py", line 113, in start_mqtt_loop
    MQTT_CLIENT = connect_mqtt()
                  ^^^^^^^^^^^^^^
  File "/share/Hyundai_Kona/mqtt_utils.py", line 97, in connect_mqtt
    client = mqtt_client.Client(mqtt_client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/Hyundai_Kona/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 772, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details

**Versions**
* hyundai_kia_connect_monitor version: R4.0.3
* Python version: 3.12
* Operating System: HomeAssistant on Raspberry Pi 5 with 8GB RAM

**Description**

When running summary.py this error occurs and has to do with MQTT settings. I assume it has to do with python library verions I've installed that differ from the makers. I cannot change these versions since these are supported by my Home Assistant on Raspberry Pi5. I'm running the latest and updated version of Home Assistant.

**What I Did**

```
Paste the command(s) you ran and the output.
python3.12 summary.py
If there was a crash, please include the traceback here.
20241222 01:26:58: ERROR: MQTT connect Exception: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details, sleeping a minute
Traceback (most recent call last):
  File "/share/Hyundai_Kona/mqtt_utils.py", line 113, in start_mqtt_loop
    MQTT_CLIENT = connect_mqtt()
                  ^^^^^^^^^^^^^^
  File "/share/Hyundai_Kona/mqtt_utils.py", line 97, in connect_mqtt
    client = mqtt_client.Client(mqtt_client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/Hyundai_Kona/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 772, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details


I've used ChatGPT to find a solution since I am only familiar with programming, but am not a coder. The solution that solves my issue is below. I can't tell if this is for everyone and if this code is compatible with other versions:
Changes to section in summary.py:
# == connect MQTT ========================================================
My change Line 96 till 103 to:
    # Use get_vin() for dynamic client ID
    mqtt_client_id = f"{MQTT_MAIN_TOPIC}-{get_vin()}"
    client = mqtt_client.Client(client_id=mqtt_client_id)  # Dynamic client ID based on VIN
    client.on_connect = on_connect
    client.on_disconnect = on_disconnect
    if MQTT_BROKER_USERNAME and MQTT_BROKER_PASSWORD:
        client.username_pw_set(MQTT_BROKER_USERNAME, MQTT_BROKER_PASSWORD)
    client.connect(MQTT_BROKER_HOSTNAME, MQTT_BROKER_PORT)
    return client
# the change is in line:     client = mqtt_client.Client(client_id=mqtt_client_id)  # Dynamic client ID based on VIN

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ZuinigeRijder** [comment]
Did you use a paho_mqtt version >= 2.0? 

Because the following version is supported ([see README](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor#how-to-install-python-packages-and-hyundai_connect_monitor)): paho_mqtt>=1.6.1,<2.0

**Comment by rpositive** [comment]
Sorry, didn't see that. I have version 2.1.0.
Does the line I changed work for earlier versions?
I will close it since this is not a bug but me using the wrong version.
Thanks for the quick reply and all the good work!
